[theme]
primaryColor = "#FF4B4B"  # Color rojo para elementos primarios
backgroundColor = "#0E1117"  # Fondo negro oscuro
secondaryBackgroundColor = "#262730"  # Color secundario oscuro para widgets
textColor = "#FAFAFA"  # Texto claro para contrastar con el fondo oscuro
font = "sans serif"

[server]
enableCORS = true  # Cambiar a true para permitir carga de recursos entre dominios
enableXsrfProtection = true
headless = true  # Añadido para mejorar la carga en entornos de despliegue

[browser]
gatherUsageStats = false  # Deshabilitar análisis para mejorar el rendimiento
serverAddress = "0.0.0.0"  # Asegurar que el servidor escucha en todas las interfaces
